# .coderabbit.yaml
# Optimized for professional PR reviews + hackathon judging
version: "2"

reviews:
  # Clear architectural context for reviewers & judges
  high_level_summary: true

  # Step-by-step explanation of changes (very OSS-friendly)
  walkthrough: true

  # CodeRabbit signature feature (kept minimal & tasteful)
  poem: true

  # Review all commits to show strong CI/review discipline
  auto_review:
    enabled: true
    on_pull_request: true
    on_commit: true

  # Focus on quality, not noise
  severity_threshold: medium

  # Ignore trivial files to keep reviews clean
  exclude:
    - "**/*.lock"
    - "**/*.min.*"
    - "**/dist/**"
    - "**/build/**"

chat:
  # Enables interactive discussions in PR comments
  auto_reply: true

  # Keep responses concise & professional
  tone: professional
