/**
 * Analysis Automation Service
 * Handles automated code analysis, email notifications, and GitHub push
 */

import { toast } from 'sonner';
import { emailReplyService } from './emailReplyService';

export interface AnalysisSettings {
  enableEmailNotifications: boolean;
  userEmail: string;
  autoGenerateImprovements: boolean;
  autoPushToGitHub: boolean;
  analysisSchedule: 'manual' | 'daily' | 'weekly' | 'on-push';
  shortReportFormat: boolean;
}

export interface AnalysisReport {
  id: string;
  timestamp: string;
  repository: string;
  totalIssues: number;
  byPriority: {
    critical: number;
    high: number;
    medium: number;
    low: number;
  };
  shortSummary: string;
  fullReport: string;
  prUrl?: string;
  emailSent: boolean;
}

class AnalysisAutomationService {
  private static instance: AnalysisAutomationService;
  private settings: AnalysisSettings = {
    enableEmailNotifications: false,
    userEmail: '',
    autoGenerateImprovements: false,
    autoPushToGitHub: false,
    analysisSchedule: 'manual',
    shortReportFormat: true
  };
  private reports: AnalysisReport[] = [];
  private readonly SETTINGS_KEY = 'analysis_automation_settings';
  private readonly REPORTS_KEY = 'analysis_reports';

  static getInstance(): AnalysisAutomationService {
    if (!AnalysisAutomationService.instance) {
      AnalysisAutomationService.instance = new AnalysisAutomationService();
    }
    return AnalysisAutomationService.instance;
  }

  constructor() {
    this.loadSettings();
    this.loadReports();
  }

  /**
   * Load settings from localStorage
   */
  private loadSettings() {
    try {
      const stored = localStorage.getItem(this.SETTINGS_KEY);
      if (stored) {
        this.settings = { ...this.settings, ...JSON.parse(stored) };
        console.log('✅ Analysis automation settings loaded');
      }
    } catch (error) {
      console.error('Failed to load settings:', error);
    }
  }

  /**
   * Load reports from localStorage
   */
  private loadReports() {
    try {
      const stored = localStorage.getItem(this.REPORTS_KEY);
      if (stored) {
        this.reports = JSON.parse(stored);
        console.log(`✅ Loaded ${this.reports.length} analysis reports`);
      }
    } catch (error) {
      console.error('Failed to load reports:', error);
    }
  }

  /**
   * Save settings to localStorage
   */
  saveSettings(newSettings: Partial<AnalysisSettings>) {
    this.settings = { ...this.settings, ...newSettings };
    try {
      localStorage.setItem(this.SETTINGS_KEY, JSON.stringify(this.settings));
      console.log('✅ Analysis automation settings saved');
      toast.success('Settings saved successfully');
    } catch (error) {
      console.error('Failed to save settings:', error);
      toast.error('Failed to save settings');
    }
  }

  /**
   * Get current settings
   */
  getSettings(): AnalysisSettings {
    return { ...this.settings };
  }

  /**
   * Generate short analysis report
   */
  generateShortReport(totalIssues: number, byPriority: any): string {
    return `📊 Code Analysis Summary
    
Total Issues: ${totalIssues}
🔴 Critical: ${byPriority.critical}
🟠 High: ${byPriority.high}
🟡 Medium: ${byPriority.medium}
🔵 Low: ${byPriority.low}

Status: Analysis complete
Generated: ${new Date().toLocaleString()}`;
  }

  /**
   * Generate full analysis report
   */
  generateFullReport(
    repository: string,
    totalIssues: number,
    byPriority: any,
    files: any[]
  ): string {
    return `# 🤖 AI Code Analysis Report

**Repository:** ${repository}
**Generated:** ${new Date().toISOString()}

## Summary
- **Total Issues:** ${totalIssues}
- **Critical:** ${byPriority.critical}
- **High:** ${byPriority.high}
- **Medium:** ${byPriority.medium}
- **Low:** ${byPriority.low}

## Issues by File
${files.map(file => `
### ${file.file}
${file.suggestions.map((s: any) => `- [${s.priority.toUpperCase()}] ${s.issue}`).join('\n')}
`).join('\n')}

---
*Generated by ResurrectCI AI Analysis*`;
  }

  /**
   * Send email notification
   */
  async sendEmailNotification(report: AnalysisReport): Promise<boolean> {
    if (!this.settings.enableEmailNotifications || !this.settings.userEmail) {
      console.log('⚠️ Email notifications disabled or no email configured');
      return false;
    }

    try {
      console.log(`📧 Sending analysis report to ${this.settings.userEmail}...`);

      // Create email reply action (for tracking user response)
      const replyAction = emailReplyService.createReplyAction(report.id, this.settings.userEmail);

      // Use Supabase edge function to send email
      const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
      const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

      if (!supabaseUrl || !supabaseKey) {
        console.warn('⚠️ Supabase not configured for email');
        return false;
      }

      const response = await fetch(`${supabaseUrl}/functions/v1/send-analysis-email`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${supabaseKey}`
        },
        body: JSON.stringify({
          to: this.settings.userEmail,
          subject: `🤖 Code Analysis Report: ${report.repository}`,
          shortReport: report.shortSummary,
          fullReport: report.fullReport,
          prUrl: report.prUrl,
          shortFormat: this.settings.shortReportFormat,
          replyId: replyAction.id,
          reportId: report.id
        })
      });

      // Parse response
      let responseData: any = {};
      try {
        responseData = await response.json();
      } catch (e) {
        console.error('Failed to parse response:', e);
      }

      if (response.ok) {
        console.log('✅ Email sent successfully:', responseData);
        report.emailSent = true;
        this.saveReport(report);
        
        if (responseData.sent) {
          toast.success(`📧 Analysis report sent to ${this.settings.userEmail}\n⏳ Waiting for your response...`);
        } else if (responseData.message?.includes('development mode')) {
          toast.info(`📧 Email service not configured (development mode)\n📧 Would send to: ${this.settings.userEmail}`);
        } else {
          toast.success(`📧 Analysis report processed\n⏳ Waiting for your response...`);
        }
        return true;
      } else {
        const errorMsg = responseData.error || responseData.message || response.statusText;
        console.error('❌ Failed to send email:', errorMsg);
        console.error('❌ Full response:', responseData);
        
        // Check if it's a configuration issue
        if (errorMsg?.includes('not configured')) {
          toast.error(`⚠️ Email service not configured\n📖 See SUPABASE_SECRETS_SETUP.md for setup instructions`);
        } else {
          toast.error(`Failed to send email: ${errorMsg}`);
        }
        return false;
      }
    } catch (error) {
      console.error('❌ Email sending error:', error);
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      toast.error(`Error sending email: ${errorMsg}`);
      return false;
    }
  }

  /**
   * Save analysis report
   */
  saveReport(report: AnalysisReport) {
    this.reports.unshift(report); // Add to beginning
    // Keep only last 50 reports
    if (this.reports.length > 50) {
      this.reports = this.reports.slice(0, 50);
    }
    try {
      localStorage.setItem(this.REPORTS_KEY, JSON.stringify(this.reports));
      console.log('✅ Report saved');
    } catch (error) {
      console.error('Failed to save report:', error);
    }
  }

  /**
   * Get all reports
   */
  getReports(): AnalysisReport[] {
    return [...this.reports];
  }

  /**
   * Get reports for specific repository
   */
  getRepositoryReports(repository: string): AnalysisReport[] {
    return this.reports.filter(r => r.repository === repository);
  }

  /**
   * Check if auto-push is enabled
   */
  shouldAutoPush(): boolean {
    return this.settings.autoPushToGitHub;
  }

  /**
   * Check if auto-generate improvements is enabled
   */
  shouldAutoGenerateImprovements(): boolean {
    return this.settings.autoGenerateImprovements;
  }

  /**
   * Check if should send email
   */
  shouldSendEmail(): boolean {
    return this.settings.enableEmailNotifications && !!this.settings.userEmail;
  }

  /**
   * Get analysis schedule
   */
  getAnalysisSchedule(): string {
    return this.settings.analysisSchedule;
  }

  /**
   * Clear all reports
   */
  clearReports() {
    this.reports = [];
    try {
      localStorage.removeItem(this.REPORTS_KEY);
      console.log('✅ Reports cleared');
      toast.success('All reports cleared');
    } catch (error) {
      console.error('Failed to clear reports:', error);
    }
  }
}

export const analysisAutomationService = AnalysisAutomationService.getInstance();
export default analysisAutomationService;
