# ResurrectCI Kestra Workflow
# This workflow orchestrates the AI agent for autonomous error fixing
# 
# Flow: Manual Trigger / API Call → Analyze Error → Search Solution → Generate Fix → Create PR
#
# To use this workflow (NO WEBHOOK REQUIRED):
# 1. Deploy to your Kestra instance (Kestra Cloud or self-hosted)
# 2. Configure secrets: SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, GITHUB_TOKEN
# 3. Trigger via: Kestra UI, API call, or ResurrectCI Dashboard
# 4. Use with Cline in VS Code for enhanced code generation

id: resurrect-agent
namespace: resurrectci
description: AI-powered autonomous build error fixing workflow

inputs:
  - id: project_id
    type: STRING
    description: Vercel project ID (primary identifier)
    
  - id: project_name
    type: STRING
    description: Name of the project/repository
    
  - id: branch
    type: STRING
    defaults: main
    description: Git branch that failed
    
  - id: error_message
    type: STRING
    description: The build error message
    
  - id: error_logs
    type: ARRAY
    itemType: STRING
    description: Detailed error logs

variables:
  supabase_url: "https://eahpikunzsaacibikwtj.supabase.co"
  max_fix_attempts: 3

tasks:
  # Step 1: Log the incoming failure
  - id: log_failure
    type: io.kestra.plugin.core.log.Log
    level: INFO
    message: |
      🚨 Build failure detected!
      Project: {{ inputs.project_name }} ({{ inputs.project_id }})
      Branch: {{ inputs.branch }}
      Error: {{ inputs.error_message }}

  # Step 2: Analyze the error using AI
  - id: analyze_error
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.supabase_url }}/functions/v1/ai-agent"
    method: POST
    contentType: application/json
    headers:
      Authorization: "Bearer {{ secret('SUPABASE_SERVICE_ROLE_KEY') }}"
    body: |
      {
        "action": "analyze_error",
        "errorInfo": {
          "projectId": "{{ inputs.project_id }}",
          "projectName": "{{ inputs.project_name }}",
          "branch": "{{ inputs.branch }}",
          "errorMessage": "{{ inputs.error_message }}",
          "errorLogs": {{ inputs.error_logs | json }},
          "timestamp": "{{ now() }}"
        }
      }

  # Step 3: Parse the analysis result
  - id: parse_analysis
    type: io.kestra.plugin.core.log.Log
    level: INFO
    message: |
      📊 Error Analysis Complete
      Result: {{ outputs.analyze_error.body }}

  # Step 4: Search for solutions
  - id: search_solution
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.supabase_url }}/functions/v1/ai-agent"
    method: POST
    contentType: application/json
    headers:
      Authorization: "Bearer {{ secret('SUPABASE_SERVICE_ROLE_KEY') }}"
    body: |
      {
        "action": "search_solution",
        "errorAnalysis": {{ outputs.analyze_error.body | json }}
      }

  # Step 5: Log found solutions
  - id: log_solutions
    type: io.kestra.plugin.core.log.Log
    level: INFO
    message: |
      🔍 Solutions Found
      Result: {{ outputs.search_solution.body }}

  # Step 6: Generate the fix
  - id: generate_fix
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.supabase_url }}/functions/v1/ai-agent"
    method: POST
    contentType: application/json
    headers:
      Authorization: "Bearer {{ secret('SUPABASE_SERVICE_ROLE_KEY') }}"
    body: |
      {
        "action": "generate_fix",
        "errorAnalysis": {{ outputs.analyze_error.body | json }},
        "searchResults": {{ outputs.search_solution.body | json }}
      }

  # Step 7: Log the generated fix
  - id: log_fix
    type: io.kestra.plugin.core.log.Log
    level: INFO
    message: |
      🔧 Fix Generated
      Result: {{ outputs.generate_fix.body }}

  # Step 8: Create GitHub branch and PR using real GitHub API
  - id: create_fix_branch
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.supabase_url }}/functions/v1/github-api"
    method: POST
    contentType: application/json
    headers:
      Authorization: "Bearer {{ secret('SUPABASE_SERVICE_ROLE_KEY') }}"
    body: |
      {
        "action": "create_branch",
        "owner": "hackerpsyco",
        "repo": "{{ inputs.project_name }}",
        "baseBranch": "{{ inputs.branch }}",
        "newBranch": "resurrect-fix-{{ now() | date('yyyyMMdd-HHmmss') }}"
      }

  # Step 9: Apply the generated fix to files
  - id: apply_fix
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.supabase_url }}/functions/v1/github-api"
    method: POST
    contentType: application/json
    headers:
      Authorization: "Bearer {{ secret('SUPABASE_SERVICE_ROLE_KEY') }}"
    body: |
      {
        "action": "update_file",
        "owner": "hackerpsyco",
        "repo": "{{ inputs.project_name }}",
        "path": "{{ outputs.generate_fix.body.filePath || 'src/App.tsx' }}",
        "content": "{{ outputs.generate_fix.body.fixedContent || '// Auto-fixed by ResurrectCI' }}",
        "message": "🤖 ResurrectCI: Automated fix for {{ inputs.error_message }}",
        "branch": "{{ outputs.create_fix_branch.body.ref }}"
      }

  # Step 10: Create Pull Request
  - id: create_pull_request
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.supabase_url }}/functions/v1/github-api"
    method: POST
    contentType: application/json
    headers:
      Authorization: "Bearer {{ secret('SUPABASE_SERVICE_ROLE_KEY') }}"
    body: |
      {
        "action": "create_pr",
        "owner": "hackerpsyco",
        "repo": "{{ inputs.project_name }}",
        "title": "🤖 ResurrectCI: Automated fix for build failure",
        "body": "## 🤖 Automated Fix by ResurrectCI\n\n**Error:** {{ inputs.error_message }}\n\n**Fix Applied:** {{ outputs.generate_fix.body.description }}\n\n### Changes:\n- Fixed build error automatically\n- Applied AI-generated solution\n- Ready for review and testing\n\n---\n*This PR was created automatically by ResurrectCI Kestra workflow.*",
        "baseBranch": "{{ inputs.branch }}",
        "newBranch": "{{ outputs.create_fix_branch.body.ref }}"
      }

  # Step 11: Notify ResurrectCI Dashboard
  - id: notify_dashboard
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.supabase_url }}/functions/v1/ai-agent"
    method: POST
    contentType: application/json
    headers:
      Authorization: "Bearer {{ secret('SUPABASE_SERVICE_ROLE_KEY') }}"
    body: |
      {
        "action": "workflow_completed",
        "workflowResult": {
          "projectId": "{{ inputs.project_id }}",
          "projectName": "{{ inputs.project_name }}",
          "status": "success",
          "prUrl": "{{ outputs.create_pull_request.body.html_url }}",
          "prNumber": "{{ outputs.create_pull_request.body.number }}",
          "fixBranch": "{{ outputs.create_fix_branch.body.ref }}",
          "completedAt": "{{ now() }}"
        }
      }

  # Step 12: Final status
  - id: success_notification
    type: io.kestra.plugin.core.log.Log
    level: INFO
    message: |
      ✅ ResurrectCI Agent Complete!
      Project: {{ inputs.project_name }}
      Status: Fix applied and PR created
      PR: {{ outputs.create_pull_request.body.html_url }}
      Branch: {{ outputs.create_fix_branch.body.ref }}

# Trigger configuration - FREE MODE WEBHOOK
triggers:
  # ✅ WEBHOOK TRIGGER (FREE MODE - NO TOKEN REQUIRED)
  - id: webhook_trigger
    type: io.kestra.plugin.core.trigger.Webhook
    key: "resurrectci"  # Must match kestraService.webhookKey
    
  # Option 2: Schedule-based polling (disabled by default)
  - id: schedule_trigger
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/5 * * * *"
    disabled: true  # Enable when ready
    
  # Option 3: Manual trigger via Kestra UI
  # Webhook URL: http://localhost:8080/api/v1/executions/webhook/resurrectci/resurrect-agent/resurrectci

# Error handling
errors:
  - id: on_failure
    type: io.kestra.plugin.core.log.Log
    level: ERROR
    message: |
      ❌ ResurrectCI Agent Failed
      Project: {{ inputs.project_name }} ({{ inputs.project_id }})
      The workflow encountered an error and could not complete the fix.
      Please check the execution logs for details.
